### ISSUE TITLE
UnRel Test Annotations

### ISSUE THREAD

**Issue by krbuettner** [kreimanlab/WhenPigsFlyContext#2]
Hi,

Do you have a COCO format file that consists of UnRel test annotations? The provided folder for UnRel seems to have only train and val jsons for COCO images which overlap in class distribution with UnRel.

Thanks!

Kyle

**Comment by bomatter** [comment]
Thank you for pointing this out Kyle! We have uploaded the test annotations and updated the README accordingly.

Best,
Philipp
